# -*- coding: utf-8 -*-
"""HealthData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lxk5fhfXuEwQzGOFxBPsOQXvpEuABT-U

#1.데이터 불러오기
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ITB/health_data.csv", encoding="utf=8")
hd = df.copy()
hd.info()

"""# 2.데이터 전처리"""

hd_null = hd.isnull().sum()
print(hd_null.sort_values(ascending = False))

hd = hd.rename(columns={'성별코드':'성별'},)

hd['성별'] = hd['성별'].replace(['M','F'], ['남자', '여자'])

hd.head()

# '치석', '치아우식증유무', 'LDL콜레스테롤', '총콜레스테롤', '트리글리세라이드', 'HDL콜레스테롤' 은 결측치가 절반(5000) 이상이므로 변수 제거

hd2 = hd.drop(columns=['치석', '치아우식증유무', 'LDL콜레스테롤', '총콜레스테롤', '트리글리세라이드', 'HDL콜레스테롤'], axis=1)
print(hd2.columns)

# 흡연상태(문자열), 음주여부(문자열)의 경우 결측치가 존재하는 행을 삭제
hd2 = hd2.dropna(subset = ['흡연상태'], axis=0)
print(hd2.shape)

hd2 = hd2.dropna(subset = ['음주여부'], axis=0)
print(hd2.shape)

# 요단백(정수형)의 경우 가장 빈도가 큰 1로 보간
hd2.groupby('요단백').count() # 최빈값이 1임을 알 수 있음

hd2['요단백'].fillna(1, inplace=True)
print(hd2.isnull().sum())

# 수축기혈압,이완기혈압,식전혈당, 혈청크레아티닌, AST, ALT, 혈색소는 평균을 사용해 대체
hd2[['수축기혈압','이완기혈압','식전혈당(공복혈당)','혈청크레아티닌','(혈청지오티)AST','(혈청지오티)ALT','혈색소']].describe()

hd2['수축기혈압'].fillna(124.668887,inplace=True)
hd2['이완기혈압'].fillna(76.789182,inplace=True)
hd2['식전혈당(공복혈당)'].fillna(103.781411,inplace=True)
hd2['혈청크레아티닌'].fillna(0.848519,inplace=True)
hd2['(혈청지오티)AST'].fillna(27.592391,inplace=True)
hd2['(혈청지오티)ALT'].fillna(26.793218,inplace=True)
hd2['혈색소'].fillna(14.214663,inplace=True)

print(hd2.isnull().sum())

# 감마지티피는 성별에 따라 정상치 기준이 다르므로 남성 결측치는 남성 평균, 여성 결측치는 여성 평균으로 대체
hd2.groupby('성별')['감마지티피'].mean()

hd2['감마지티피'].fillna(0,inplace=True) # 결측치를 0으로 채워주기

hd2.loc[(hd['성별']=='여자')&(hd2['감마지티피']==0),'감마지티피']=25.226800
hd2.loc[(hd['성별']=='남자')&(hd2['감마지티피']==0),'감마지티피']=50.233196

hd2.isnull().sum() #결측치 처리 완료

hd2.info()

"""# 3.데이터 시각화"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import seaborn as sns

import matplotlib as mpl
import matplotlib.pyplot as plt

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

plt.rcParams['font.family'] = ['NanumBarunGothic', 'Malgun Gothic', 'AppleGothic']
plt.rcParams['axes.unicode_minus'] = False

plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['font.family'] = 'Malgun Gothic'

hd2.columns

"""## 1)성별에 따른 흡연여부"""

hd2 = hd2.rename(columns={'음주여부':'drink'},)

hd2 = hd2.rename(columns={'성별':'gender'},)

hd2['gender'] = hd2['gender'].replace(['남자','여자'], ['Male', 'Female'])

sns.countplot(data=hd2,x='drink', hue='gender')

"""=> 흡연자 남성이 흡연자 여성보다 2배 가까이 많으며, 비흡연자 여성이 비흡연자 남성보다 2배 가까이 많다.

## 2)AST와 ALT
"""

hd2 = hd2.rename(columns={'(혈청지오티)AST':'AST'},)
hd2 = hd2.rename(columns={'(혈청지오티)ALT':'ALT'},)

print(hd2['ALT'].min())
print(hd2['ALT'].max())
print(hd2['AST'].min())
print(hd2['AST'].max())

print(hd2['ALT'].describe())
print("")
print(hd2['AST'].describe())

sns.scatterplot(data = hd2, x = 'AST', y = 'ALT').set(xlim = (3, 500), ylim = (2, 600))

"""=> 우상향하는 그래프로, AST가 높으면 ALT도 높은 경향을 보임을 알 수 있다.

## 3)음주여부-허리둘레-성별 간 관계
"""

hd2 = hd2.rename(columns={'허리둘레':'WAIST'},)

ax = plt.subplots()
ax = sns.violinplot(data=hd2, x='drink',y='WAIST', hue='gender',split=True)

"""=> 음주를 하는 사람일수록 허리둘레가 클 것이라 추정했으나, 그래프를 그려 본 결과 예상과 달리 둘 사이에 큰 상관관계는 없는 것으로 추정된다. 오히려 음주를 하지 않는 집단의 바이올린 꼬리가 더 긴 것으로 보아, 음주하지 않는 집단 중 허리둘레가 매우 큰 사람(이상치)가 음주하는 집단보다 더 많은 것으로 파악된다."""